### ISSUE TITLE
Use gradle orb

### ISSUE THREAD

**Issue by devatherock** [devatherock/velocity-template-tester#15]
Might need to use [post-steps](https://circleci.com/docs/2.0/reusing-config/#using-pre-and-post-steps) to persist the jar file to the workspace, to be used in the next job

Possible config:
```yml
post-steps:
  - persist_to_workspace:
      root: ~/velocity-template-tester
      paths:
        - build
```
